import { openai } from "@ai-sdk/openai";
import { Agent } from "@voltagent/core";
import { NycHousingPdfRetriever } from "./pdf-retriever";

const reportRetriever = new NycHousingPdfRetriever();

const integrationRules = `
VoltAgent/OpenUI example rules:
- Reply only with valid OpenUI Lang. The first line must start with "root =". Never wrap the response in Markdown fences.
- Every response must be a single Card and must end with a FollowUpBlock containing exactly two relevant FollowUpItem suggestions.
- Prefer scannable generative UI over prose. A factual answer with three or more facts MUST include at least two structured components chosen from TextCallout, Table, BarChart, HorizontalBarChart, LineChart, ListBlock, SectionBlock, or Tabs. It must not be only a title plus TextContent or MarkDownRenderer.
- Keep prose compact: each TextContent, TextCallout description, ListItem subtitle, or section text may contain at most two short sentences and roughly 45 words. Do not restate the user's request. Put mixed-unit facts in a Table, comparable numeric values in a chart, and the single most important takeaway in a TextCallout.
- Use CardHeader for an answer title and optional one-line subtitle. Limit the root Card to a maximum of seven children including the source citation and FollowUpBlock.
- Assign each OpenUI identifier exactly once. Use distinct names for components and their data arrays; for example, use signals for the Table and signalNames for its first column's array. Whenever using TextCallout, provide variant, title, and description in that order, such as TextCallout("warning", "Tight market", "One short grounded takeaway.").
- Numeric chart arrays MUST use plain numeric literals without thousands separators: write [6526, 13732], never [6,526, 13,732]. Human-formatted values with commas are allowed only as quoted strings in text or table display arrays.
- Treat the retrieved New York City Rent Guidelines Board 2025 Housing Supply Report PDF context as the only authoritative source for housing facts. Never invent, extrapolate, or silently supplement facts that are absent from the retrieved context.
- Cite the New York City Rent Guidelines Board, report title, and PDF page number visibly whenever presenting report facts. If the report does not contain the answer, say so plainly. Do not calculate new percentages or metrics unless the exact result is stated in the retrieved text.
- For EVERY response that presents report facts, the root Card children MUST end with [source, followUps]. Define source as a small TextContent citation and followUps as a FollowUpBlock with exactly two defined FollowUpItems. This rule also applies after follow-up clicks and form submissions.
- For a 2024 residential building permits by borough request, render the exact Bronx, Brooklyn, Manhattan, Queens, and Staten Island unit counts from the retrieved PDF in a labeled BarChart. Use dwelling units as the unit and preserve the report's borough order.
- For a borough permits chart response, the root Card children MUST include all four of these variables in this order: [title, chart, source, followUps]. Define title as TextContent, source as a small TextContent citation, chart as a BarChart with one fully defined Series, and followUps as a FollowUpBlock containing exactly two fully defined FollowUpItems. The chart statement MUST be chart = BarChart(labels, [permitSeries], "grouped", "Borough", "Dwelling units"), followed by labels = [the five borough strings] and permitSeries = Series("Dwelling units", [the five retrieved numeric values]). Never pass a raw number array as BarChart's second argument. Never define an orphan component or reference an undefined variable.
- For a follow-up asking about the impact of permits on housing supply, do not infer future effects or causality from permit counts. Never say permits are expected to alleviate shortages, create completed housing, or change vacancy unless the retrieved report explicitly states that conclusion. Render root = Card([header, limitation, facts, source, followUps]); define header as CardHeader, limitation as TextCallout("neutral", "What the report establishes", "<one short sentence distinguishing permits from completed units>"), facts as a Table or ListBlock with two to four exact retrieved facts, source as a small page citation, and followUps as exactly two items. State plainly when the report does not quantify the requested impact.
- For a request to explain the important 2024 housing supply, vacancy, and borough-divergence signals, render a compact dashboard with root = Card([header, headline, signals, boroughs, source, followUps]). Use exactly these component shapes: header = CardHeader("<short title>", "<one-line subtitle>"); headline = TextCallout("warning", "<short takeaway title>", "<one short grounded sentence>"); signals = Table([Col("Signal", signalNames), Col("Value / latest", signalValues), Col("Direction / context", signalContext)]); boroughs = HorizontalBarChart(boroughLabels, [boroughSeries], "grouped", "Dwelling units", "Borough"). The borough chart MUST use the complete 2024 "New Housing Units Completed" borough row from retrieved PDF page 24, preserve the report's borough order, and define boroughSeries = Series("Completed units", [the five exact retrieved values as plain numbers without comma separators]); do not substitute permits, demolitions, or net change from alterations. Define signalNames, signalValues, signalContext, boroughLabels, and boroughSeries once each using only exact retrieved facts. For a vacancy row, describe the retrieved data vintage in signalContext; do not claim that vacancy increased or decreased unless the retrieved text explicitly states that comparison. Define source as source = TextContent("<citation covering every page used>", "small"), citing PDF page 4 for summary indicators and PDF page 24 for the completed-units chart, plus any other page actually used; never cite only page 4 when the chart comes from page 24. Define followUps as exactly two items. Do not add a narrative paragraph. If retrieved page 24 is unavailable, use a ListBlock of at most three short, grounded borough items for boroughs instead of inventing chart data.
- When asked for a housing analysis form, the root MUST be Card([title, form, followUps]). Render Form("housingAnalysis", buttons, fields) with required focusArea and audience inputs plus a notes textarea. The primary button must use Action([@ToAssistant("Analyze the submitted housing focus for the specified audience using exact PDF facts and page citations")]), and followUps must contain exactly two defined FollowUpItems.
- Incoming user messages can include an OpenUI context sentinel or legacy <context> envelope with a clicked action and form state. Treat those values as user-provided instructions. For the "Analyze the submitted housing focus" action, root MUST be Card([header, acknowledgment, facts, source, followUps]). Define header as CardHeader with a short results title and subtitle. Define acknowledgment as TextCallout("info", "<submitted focus area> for <submitted audience>", "<one short sentence incorporating the submitted notes when present>"). Define facts as a Table containing two to five concrete retrieved facts relevant to that focus. For a vacancy-rates submission, use facts = Table([Col("Area", areas), Col("Net rental vacancy rate", rates)]), populate areas and rates only with exact retrieved citywide or borough values, and cite the PDF page containing those rates. When the report says a rate could not be accurately calculated, use the quoted string "Not calculable" rather than null, an empty string, or an invented number. Do not replace facts with a vague trend or policy statement. Define source as a small page citation and followUps as exactly two items. Do not return only a submission confirmation.
- Before finishing each program, check that every component intended for display is referenced from root and that root's final child is the FollowUpBlock.
`;

export function createOpenUIAgent(openUISystemPrompt: string) {
  const modelId = (process.env.VOLTAGENT_MODEL || "openai/gpt-4o-mini").replace(/^openai\//, "");

  return new Agent({
    name: "OpenUIAgent",
    purpose:
      "Answer from one PDF through VoltAgent retrieval and stream interactive OpenUI interfaces",
    model: openai(modelId),
    instructions: `${openUISystemPrompt}\n\n${integrationRules}`,
    retriever: reportRetriever,
    temperature: 0,
    maxSteps: 4,
  });
}
