name: Prerelease

on:
  push:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This will run pnpm changeset version and create a PR
          version: pnpm changeset version
          # This will run pnpm changeset publish --tag next
          publish: pnpm changeset publish --tag next
          title: '[Prerelease] Version Packages (next)'
          commit: 'chore: version packages (prerelease)'
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
