name: Prerelease

on:
  push:
    branches:
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - cli
          - core
          - create-voltagent-app
          - docs-mcp
          - internal
          - langfuse-exporter
          - logger
          - postgres
          - sdk
          - supabase
          - vercel-ai-exporter
          - voice
      fail-fast: false
    name: Test ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
      - name: Set package scope
        id: scope
        run: |
          if [[ "${{ matrix.package }}" == "create-voltagent-app" ]]; then
            echo "scope=create-voltagent-app" >> $GITHUB_OUTPUT
          else
            echo "scope=@voltagent/${{ matrix.package }}" >> $GITHUB_OUTPUT
          fi
      - name: Build Package and Dependencies
        run: lerna run build --scope "${{ steps.scope.outputs.scope }}" --include-dependencies
      - name: Test Package
        run: lerna run test --scope "${{ steps.scope.outputs.scope }}"

  prerelease:
    name: Prerelease
    needs: test-packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: read
      pull-requests: write
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: voltagent_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VOLTAGENT_BOT }}
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: pnpm install
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Build All Packages
        run: pnpm build:all
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'

      - name: Lint with Biome
        run: pnpm lint:ci

      - name: Syncpack
        run: pnpm sp lint

      - name: Publint
        run: pnpm publint:all

      - name: Are The Types Wrong
        run: pnpm attw:all

      - name: PostgreSQL Integration Tests
        run: |
          cd packages/postgres
          npm run test:integration:ci
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/voltagent_test

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This will run pnpm version-packages which handles prerelease mode
          version: pnpm version-packages
          # This will run pnpm changeset publish (tag is handled by pre mode)
          publish: pnpm changeset publish
          title: '[Prerelease] Version Packages'
          commit: 'chore: version packages (prerelease)'
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.VOLTAGENT_BOT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
