name: Release

on:
  push:
    branches:
      - main

jobs:
  test-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - anthropic-ai
          - cli
          - core
          - create-voltagent-app
          - docs-mcp
          - google-ai
          - groq-ai
          - internal
          - langfuse-exporter
          - logger
          - postgres
          - sdk
          - supabase
          - vercel-ai
          - vercel-ai-exporter
          - vercel-ui
          - voice
          - xsai
      fail-fast: false
    name: Test ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
      - name: Set package scope
        id: scope
        run: |
          if [[ "${{ matrix.package }}" == "create-voltagent-app" ]]; then
            echo "scope=create-voltagent-app" >> $GITHUB_OUTPUT
          else
            echo "scope=@voltagent/${{ matrix.package }}" >> $GITHUB_OUTPUT
          fi
      - name: Build Package and Dependencies
        run: lerna run build --scope "${{ steps.scope.outputs.scope }}" --include-dependencies
      - name: Test Package
        run: lerna run test --scope "${{ steps.scope.outputs.scope }}"

  publish:
    needs: test-packages
    permissions:
      contents: write
      id-token: write
      issues: read
      pull-requests: write
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-stable-release
      cancel-in-progress: true
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: voltagent_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.VOLTAGENT_BOT }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies
        run: pnpm install
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
      - name: Build
        run: pnpm build:all
      - name: Lint with Biome
        run: pnpm lint:ci
      - name: Syncpack
        run: pnpm sp lint
      - name: Publint
        run: pnpm publint:all
      - name: Are The Types Wrong
        run: pnpm attw:all

      - name: PostgreSQL Integration Tests
        run: |
          cd packages/postgres
          npm run test:integration:ci
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/voltagent_test
      
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm version-packages
          publish: pnpm changeset publish
          commit: "ci(changesets): version packages"
          title: "ci(changesets): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.VOLTAGENT_BOT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
